### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by SyberiaKey** [ReviversMC/microDurability#10]

**Comment by NebelNidas** [comment]
What specifically would you like to be localized? Since the mod itself doesn't add any prompts 🤔

**Comment by SyberiaKey** [comment]
Well, what about settings menu?
![изображение](https://user-images.githubusercontent.com/97897772/172607369-bbdbf0ed-fa0d-4248-93ee-11d8a822b4e7.png)

**Comment by SyberiaKey** [comment]
Oh, wait, i found localization files, sorry 😅

**Comment by NebelNidas** [comment]
Yeah, it's default AutoConfig stuff ;)

**Comment by SyberiaKey** [comment]
Noticed these comment strings, is there any way to localize them?
![изображение](https://user-images.githubusercontent.com/97897772/172897831-5336fa2b-75e1-41de-aa82-8bc6769716a8.png)

**Comment by SyberiaKey** [comment]
Ok, I finally got my hands to this thing and solved the problem. I'll do PR in few minutes :)
