### ISSUE TITLE
Compatibility with Raised

### ISSUE THREAD

**Issue by jn64** [ReviversMC/microDurability#11]
Would it be possible to add compatibility with [Raised](https://github.com/yurisuika/Raised)? It raises the hotbar by a certain amount.

Here's an example of a mod adding compatibility (1 liner): https://github.com/intact/arrows-info/commit/0ad63cbb49d00732c2582000e82fccf33d292115

**Comment by yurisuika** [comment]
Hey, just letting you know that I've refactored stuff in version 1.2.0. `distance` is now `hud` and `offset` is now `chat`.

**Comment by NebelNidas** [comment]
Thanks, I'll push an update soon!

**Comment by NebelNidas** [comment]
"soon" was an overestimation, but 0.4.0 now supports both the old and new ObjectShare IDs :)
