### ISSUE TITLE
Chinese simplified translation.

### ISSUE THREAD

**Issue by IJustWantANamePlease** [ReviversMC/microDurability#19]
Hello there! I have done Chinese (Simplified) translation for this mod. Sadly I have no knowledge in modding or coding, so I guess opening an issue is safer. If mod translation works the same way as resourcepacks do, there should be no problem. : )
Also there is a suggestion about the Chinese translation of the mod's name. In the uploaded file I kept "microDurability", but  for complete localisation I would suggest name "极简耐久显示". It means "Minimalist Durability Viewer". I would update the file if this name is accepted.
(The file is compressed as GitHub does not accept json.)
[zh_cn.zip](https://github.com/ReviversMC/microDurability/files/8949196/zh_cn.zip)

**Comment by IJustWantANamePlease** [comment]
Sure, I'll keep it unchanged then.

**Comment by NebelNidas** [comment]
Resolved via #20 :)
