### ISSUE TITLE
y offset

### ISSUE THREAD

**Issue by Hu1night** [ReviversMC/microDurability#22]
https://user-images.githubusercontent.com/102896414/184807876-47b62309-4df3-4e54-9b8e-90b1699352ab.mp4

**Comment by NebelNidas** [comment]
Uhm, it seems like the video is broken, could you please re-upload it? Or describe the issue in words?

**Comment by Hu1night** [comment]
well This video is encoded with h265
![20230129145206](https://user-images.githubusercontent.com/102896414/215310192-eb723f31-2532-4776-b25c-8a2ddd2d4392.png)
![20230129145224](https://user-images.githubusercontent.com/102896414/215310201-90d86871-60cc-4355-a487-046cfd066f5a.png)

**Comment by NebelNidas** [comment]
Thanks! Should be very easy to fix, I'll look into it later today.

**Comment by FaultyFunctions** [comment]
Any update on this?

**Comment by NebelNidas** [comment]
0.4.0 now has native support for the Double Hotbar mod, but I also included the manual offset option just in case someone has a use for it. Sorry for that _slight_ delay though 😅

**Comment by Hu1night** [comment]
haha that is fine, I even want to modify it by myself
