### ISSUE TITLE
[Feature Request] Show full durability with some else colour like white

### ISSUE THREAD

**Issue by IJustWantANamePlease** [ReviversMC/microDurability#5]
Hey I would like to ask if it is possible to change the colour of full durability to a different one e.g. white.
I'm suggesting this because when using experience to restore mending armour it's hard to know if it has completed, and I don't really like hiding full durability, which makes me feel like I'm wearing nothing.

**Comment by NebelNidas** [comment]
Good idea! Shouldn't be that hard to implement, you'll have to wait one or two weeks though since I don't have much time currently :)

**Comment by vos6434** [comment]
Could you also add a config to remove the durability bars? I'm using this mod for the crosshair durability warning.

**Comment by SebaSphere** [comment]
> Could you also add a config to remove the durability bars? I'm using this mod for the crosshair durability warning.

Should be added in this PR - https://github.com/ReviversMC/microDurability/pull/9

**Comment by SyberiaKey** [comment]
Hey! I have some progress. Hope I get it done pretty quickly.
![testing_bars](https://us-east-1.tixte.net/uploads/syberiak.is-from.space/javaw_sHRZk6Ae2G.gif)

**Comment by NebelNidas** [comment]
Implemented via #15 :)
